spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/autoluxe
    username: postgres
    password: bestuser
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: samdim2018@gmail.com
    password: uzzoqpcvhpfhwxuk
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            required: true
          auth: true
          debug: false





logging:
  level:
    org:
      springframework:
        security: TRACE
      hibernate:
        SQL: debug


app:
  auth:
    tokenSecret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
    tokenExpirationMsec: 86400000
    refreshExpirationMsec: 864000000

JWT_ACCESS_COOKIE_NAME: access_token
JWT_REFRESH_COOKIE_NAME: refresh_token